#############################################################################
# Makefile for building: StudioPlusPlus
# Generated by qmake (3.0) (Qt 5.1.0) on: So 4. Aug 11:11:36 2013
# Project:  StudioPlusPlus.pro
# Template: subdirs
# Command: C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\bin\qmake.exe -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile StudioPlusPlus.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-sppbrowser \
		sub-Studio


sub-sppbrowser-qmake_all:  FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	cd sppbrowser\ && $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && $(MAKE) -f Makefile qmake_all
sub-sppbrowser: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-sppbrowser-make_first: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-sppbrowser-all: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-sppbrowser-clean: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-sppbrowser-distclean: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-sppbrowser-install_subtargets: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-sppbrowser-uninstall_subtargets: FORCE
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Studio-qmake_all:  FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	cd Studio\ && $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && $(MAKE) -f Makefile qmake_all
sub-Studio: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Studio-make_first: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Studio-all: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Studio-clean: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Studio-distclean: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Studio-install_subtargets: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Studio-uninstall_subtargets: FORCE
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: StudioPlusPlus.pro C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\common\shell-win32.conf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\qconfig.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_bootstrap.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_clucene.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_declarative.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_designercomponents.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_platformsupport.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmldevtools.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_quickparticles.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_v8.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkit.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\spec_post.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\qml_debug.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\declarative_debug.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\win32\rtti.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\lex.prf \
		StudioPlusPlus.pro
	$(QMAKE) -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile StudioPlusPlus.pro
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\common\shell-win32.conf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\qconfig.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_bootstrap.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_clucene.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_designercomponents.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_platformsupport.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmldevtools.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_quickparticles.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_v8.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\spec_post.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\default_post.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\qml_debug.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\declarative_debug.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\win32\rtti.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\yacc.prf:
C:\Qt\Qt5.1.0_msvc2012\5.1.0\msvc2012\mkspecs\features\lex.prf:
StudioPlusPlus.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile StudioPlusPlus.pro

qmake_all: sub-sppbrowser-qmake_all sub-Studio-qmake_all FORCE

make_first: sub-sppbrowser-make_first sub-Studio-make_first FORCE
all: sub-sppbrowser-all sub-Studio-all FORCE
clean: sub-sppbrowser-clean sub-Studio-clean FORCE
distclean: sub-sppbrowser-distclean sub-Studio-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-sppbrowser-install_subtargets sub-Studio-install_subtargets FORCE
uninstall_subtargets: sub-sppbrowser-uninstall_subtargets sub-Studio-uninstall_subtargets FORCE

sub-sppbrowser-sub_Debug:
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-Studio-sub_Debug:
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-sppbrowser-sub_Debug sub-Studio-sub_Debug

sub-sppbrowser-sub_Release:
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-Studio-sub_Release:
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-sppbrowser-sub_Release sub-Studio-sub_Release

sub-sppbrowser-check:
	@if not exist sppbrowser\ mkdir sppbrowser\ & if not exist sppbrowser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd sppbrowser\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\sppbrowser\sppbrowser.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Studio-check:
	@if not exist Studio\ mkdir Studio\ & if not exist Studio\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Studio\ && ( if not exist Makefile $(QMAKE) D:\_projekte\StudioPlusPlus\Studio\Studio.pro -spec win32-msvc2012 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-sppbrowser-check sub-Studio-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

